# rule identifiers to exclude from running
disabled_rules:
  - line_length

opt_in_rules:
  

# paths to include during linting. `--path` is ignored if present.
included:
  

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  

# configurable rules can be customized from this configuration file
# binary rules can set their severity level  
force_cast: warning
